services:
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    environment:
      TZ: "UTC"
      NVIDIA_VISIBLE_DEVICES: "all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command: ["--model", "/models/Qwen3.6-35B-A3B-UD-IQ1_M.gguf", "--flash-attn", "on", "--ctx-size", "100000"]
